version: '3'

services:

  wordpress:
    image: wordpress
    container_name: sallmedia_wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: Cd49poLn6y9o
    working_dir: /var/www/html
    volumes:
      - ./wp-content/:/var/www/html/wp-content

  mysql:
    image: mariadb
    container_name: sallmedia_mysql
    ports:
      - 3886:3306
    environment:
      MYSQL_ROOT_PASSWORD: Cd49poLn6y9o
